name: Docker

on:
  pull_request:
    branches:
      - '**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  TEST_TAG: tmd:test

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      # This is intended to address disk space issues that have surfaced
      # intermittently during CI -
      # https://github.com/actions/runner-images/issues/2840#issuecomment-1284059930
      # https://github.com/orgs/community/discussions/25678#discussioncomment-5242449
      - name: Free up space in /dev/root
        run: |
          echo "Disk usage before clean up:"
          df -h
          du -sch $AGENT_TOOLSDIRECTORY/* | sort -rh
          sudo rm -rf $AGENT_TOOLSDIRECTORY/
          sudo rm -rf /usr/share/dotnet
          echo "Disk usage after clean up:"
          df -h
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Container
        uses: docker/build-push-action@v6
        with:
          load: true
          tags: ${{ env.TEST_TAG }}
          build-args: CUDA_ARCH=75

      - name: Test Import
        run: |
          docker run --rm ${{ env.TEST_TAG }} python -c 'from tmd.lib.custom_ops import Context_f32; print("success")'
